import express from "express";
import { exec } from "child_process";
import path from "path";
import { existsSync, unlinkSync } from "fs";

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 9000;

// List of public YouTube-only download endpoints (no cookies, no PoToken complications)
app.get("/", (req, res) => {
    res.json({
        name: "yt-downloader",
        status: "running",
        message: "POST /api/download with body { url, format?, quality? }",
        formats: ["mp4", "mp3"],
        qualities: ["144", "360", "720", "1080", "1440", "2160"]
    });
});

app.post("/api/download", (req, res) => {
    const { url, format = "mp4", quality = "720" } = req.body || {};
    if (!url) return res.status(400).json({ error: "URL required" });

    const outFile = path.join("/tmp", `dl_${Date.now()}.%(ext)s`);
    const args = [
        "--no-playlist",
        "--no-warnings",
        "--no-check-certificate",
        "-o", outFile,
        "--extractor-args", "youtube:player_client=android,web",
        url,
    ];

    if (format === "mp3") {
        args.unshift("-x", "--audio-format", "mp3");
    } else {
        args.unshift("-f", `bestvideo[height<=${quality}][ext=mp4]+bestaudio[ext=m4a]/best[height<=${quality}][ext=mp4]/best`);
        args.unshift("--merge-output-format", "mp4");
    }

    const cmd = `yt-dlp ${args.join(" ")}`;
    console.log("Running:", cmd);

    exec(cmd, { timeout: 300000 }, (error, stdout, stderr) => {
        if (error) {
            console.error("yt-dlp error:", stderr);
            return res.status(500).json({ error: stderr || error.message });
        }
        console.log("yt-dlp stdout:", stdout);
        // The downloaded filename was generated by yt-dlp based on %(ext)s
        // We need to find the actual file in /tmp
        const files = require("fs").readdirSync("/tmp").filter(f => f.startsWith("dl_"));
        const lastFile = files.map(f => ({ f, m: require("fs").statSync(path.join("/tmp", f)).mtime.getTime() }))
            .sort((a, b) => b.m - a.m)[0];
        if (!lastFile) return res.status(500).json({ error: "File not found after download" });

        const filepath = path.join("/tmp", lastFile.f);
        res.download(filepath, lastFile.f, (err) => {
            if (err) console.error("Send error:", err);
            try { unlinkSync(filepath); } catch {}
        });
    });
});

app.listen(PORT, () => console.log(`yt-downloader listening on ${PORT}`));
